wechat_id: inmusichome #replace this with your wechat id
help_message: your help message
welcome_message:
  title: In Music Pty Ltd
  picture: http://www.in-music.com.au/inmusic/HebeYogaPoster.jpg
  description: 田馥甄與林宥嘉 Love In Music Concert
  link: http://www.in-music.com.au/weixinggk/
